services:

  # MongoDB
  mongodb:
    image: mongo:latest
    pull_policy: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: abhi
      MONGO_INITDB_ROOT_PASSWORD: supersecretpassword
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    networks:
      - app_network
    restart: always



  elastic_search:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
      container_name: elastic_search
      networks:
        - app_network
      ports:
        - '9200:9200'
      volumes:
        - elastic_data_container:/usr/share/elasticsearch/data
      environment:
        - cluster.name=my-es-cluster
        - node.name=node-1
        - discovery.type=single-node
        - xpack.security.enabled=false
networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data_container:
  elastic_data_container:

